version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly
  tests: true

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign # finds wasted assignment statements
  settings:
    revive:
      rules:
        # default rules
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
        # enabled or tweaked by us
        - name: use-any
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    forbidigo:
      forbid:
        - pattern: http\.NotFound.*
        - pattern: http\.Error.*
    funlen:
      lines: 100
    gomoddirectives:
      replace-allow-list:
        - github.com/abbot/go-http-auth
    nestif:
      min-complexity: 6
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dogsled
          - dupl
          - funlen
          - gosec
        path: _test\.go
      - linters:
          - cyclop
          - goconst
          - staticcheck
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
